/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlykhoahoc.UI;

import com.mycompany.quanlykhoahoc.BLL.StudentBLL;
import com.mycompany.quanlykhoahoc.Entity.Student;
import com.mycompany.quanlykhoahoc.Static.Model_Button;
import com.mycompany.quanlykhoahoc.Utils.CustomTable;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manh Hai
 */
public class StudentMainForm extends javax.swing.JPanel {
    private static CustomTable customTable = new CustomTable();
    private static StudentBLL studentBLL = new StudentBLL();
    
    private int count, soTrang, trang = 1;
    

    /**
     * Creates new form Form_Home
     */
    public StudentMainForm() {
        initComponents();
        btn_them.setData(new Model_Button("ADD"));
        btn_sua.setData(new Model_Button("UPDATE"));
        btn_xoa.setData(new Model_Button("DELETE"));
        
        customTable.customTable(jTable_Student);
        customTable.customTableHeader(jTable_Student, new Color(42, 187, 155), 14);
        
        populateJtableWithStudents(1);
        
        setPagination();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new com.mycompany.quanlykhoahoc.Component.Card();
        panel = new javax.swing.JLayeredPane();
        btn_them = new com.mycompany.quanlykhoahoc.Component.Card();
        btn_sua = new com.mycompany.quanlykhoahoc.Component.Card();
        btn_xoa = new com.mycompany.quanlykhoahoc.Component.Card();
        panelBorder1 = new com.mycompany.quanlykhoahoc.Component.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Student = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_dau = new javax.swing.JButton();
        jButton_prev = new javax.swing.JButton();
        jLabel_trang = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jButton_cuoi = new javax.swing.JButton();
        jLabel_so_trang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchText = new com.mycompany.quanlykhoahoc.Component.SearchText();
        jLabel_CloseForm_1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 240, 240));

        panel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btn_them.setColor1(new java.awt.Color(186, 123, 247));
        btn_them.setColor2(new java.awt.Color(167, 94, 236));
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });
        panel.add(btn_them);

        btn_sua.setColor1(new java.awt.Color(241, 208, 62));
        btn_sua.setColor2(new java.awt.Color(211, 184, 61));
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });
        panel.add(btn_sua);

        btn_xoa.setColor1(new java.awt.Color(142, 142, 250));
        btn_xoa.setColor2(new java.awt.Color(123, 123, 245));
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });
        panel.add(btn_xoa);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jTable_Student.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Student);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton_dau.setBackground(new java.awt.Color(242, 240, 240));
        jButton_dau.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_dau.setText("<<");
        jButton_dau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dauActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_dau);

        jButton_prev.setBackground(new java.awt.Color(242, 240, 240));
        jButton_prev.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_prev.setText("<");
        jButton_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prevActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_prev);

        jLabel_trang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_trang.setText("0");
        jPanel1.add(jLabel_trang);

        jButton_next.setBackground(new java.awt.Color(242, 240, 240));
        jButton_next.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_next.setText(">");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_next);

        jButton_cuoi.setBackground(new java.awt.Color(242, 240, 240));
        jButton_cuoi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_cuoi.setText(">>");
        jButton_cuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cuoiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cuoi);

        jLabel_so_trang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_so_trang.setText("0/0");
        jPanel1.add(jLabel_so_trang);

        jButton1.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextKeyPressed(evt);
            }
        });

        jLabel_CloseForm_1.setBackground(new java.awt.Color(1, 152, 117));
        jLabel_CloseForm_1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_CloseForm_1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_1.setText("X");
        jLabel_CloseForm_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm_1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm_1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentMouseClicked
        int index = jTable_Student.getSelectedRow();
        
        String firstName = jTable_Student.getValueAt(index, 1).toString();
        String lastName = jTable_Student.getValueAt(index, 2).toString();
        String enrollmentDate = jTable_Student.getValueAt(index, 3).toString();
        
        
    }//GEN-LAST:event_jTable_StudentMouseClicked

    private void jButton_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prevActionPerformed
        if(trang > 1) {
            trang--;
            populateJtableWithStudents(trang);
            jLabel_trang.setText(""+trang);
            jLabel_so_trang.setText(trang+"/"+soTrang);
        }
    }//GEN-LAST:event_jButton_prevActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        if(trang < soTrang) {
            trang++;
            populateJtableWithStudents(trang);
            jLabel_trang.setText(""+trang);
            jLabel_so_trang.setText(trang+"/"+soTrang);
        }
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_dauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dauActionPerformed
        trang = 1;
        populateJtableWithStudents(trang);
        jLabel_trang.setText("1");
        jLabel_so_trang.setText("1/"+soTrang);
    }//GEN-LAST:event_jButton_dauActionPerformed

    private void jButton_cuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cuoiActionPerformed
        trang = soTrang;
        populateJtableWithStudents(trang);
        jLabel_trang.setText(""+soTrang);
        jLabel_so_trang.setText(soTrang+"/"+soTrang);
    }//GEN-LAST:event_jButton_cuoiActionPerformed

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        StudentAddForm addStudent = new StudentAddForm();
        addStudent.setVisible(true);
    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        StudentEditForm editStudent = new StudentEditForm();
        editStudent.setVisible(true);
    }//GEN-LAST:event_btn_suaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateJtableWithStudents(trang);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        StudentDeleteForm deleteStudent = new StudentDeleteForm();
        deleteStudent.setVisible(true);
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyPressed
        String fullname = searchText.getText();
        populateJtableWithFullname(fullname);
    }//GEN-LAST:event_searchTextKeyPressed


    public void populateJtableWithStudents(int trang) {
        ArrayList<Student> studentList = (ArrayList<Student>) studentBLL.LoadStudents(trang);
        
        // jtable columns
        String[] colNames = {"ID","FIRST NAME", "LAST NAME","ENROLLMENT DATE"};
        
        // jtable rows
        Object[][] rows = new Object[studentList.size()][colNames.length];
        
        for(int i = 0; i < studentList.size(); i++) {
            rows[i][0] = studentList.get(i).getPersonId();
            rows[i][1] = studentList.get(i).getFirstName();
            rows[i][2] = studentList.get(i).getLastName();
            rows[i][3] = studentList.get(i).getEnrollmentDate();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Student.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.quanlykhoahoc.Component.Card btn_sua;
    private com.mycompany.quanlykhoahoc.Component.Card btn_them;
    private com.mycompany.quanlykhoahoc.Component.Card btn_xoa;
    private com.mycompany.quanlykhoahoc.Component.Card button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cuoi;
    private javax.swing.JButton jButton_dau;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CloseForm_1;
    private javax.swing.JLabel jLabel_so_trang;
    private javax.swing.JLabel jLabel_trang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Student;
    private javax.swing.JLayeredPane panel;
    private com.mycompany.quanlykhoahoc.Component.PanelBorder panelBorder1;
    private com.mycompany.quanlykhoahoc.Component.SearchText searchText;
    // End of variables declaration//GEN-END:variables

    private void setPagination() {
        count = studentBLL.countRecordStudent();
        if(count % 15 == 0) {
            soTrang = count / 15;
        } else {
            soTrang = count / 15 + 1;
        }
        jLabel_trang.setText("1");
        jLabel_so_trang.setText("1/" + soTrang);
    }
    
    public void populateJtableWithFullname(String fullname) {
        ArrayList<Student> studentList = (ArrayList<Student>) studentBLL.findStudent(fullname);
        
        // jtable columns
        String[] colNames = {"ID","FIRST NAME", "LAST NAME","ENROLLMENT DATE"};
        
        // jtable rows
        Object[][] rows = new Object[studentList.size()][colNames.length];
        
        for(int i = 0; i < studentList.size(); i++) {
            rows[i][0] = studentList.get(i).getPersonId();
            rows[i][1] = studentList.get(i).getFirstName();
            rows[i][2] = studentList.get(i).getLastName();
            rows[i][3] = studentList.get(i).getEnrollmentDate();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Student.setModel(model);
    }
   
}
