/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlykhoahoc.Component;

import com.mycompany.quanlykhoahoc.Static.Model_Button;
import java.awt.Color;
import javax.swing.plaf.basic.BasicScrollBarUI;

/**
 *
 * @author Manh Hai
 */
public class Form_Home extends javax.swing.JPanel {

    /**
     * Creates new form Form_Home
     */
    public Form_Home() {
        initComponents();
        btn_them.setData(new Model_Button("ADD"));
        btn_sua.setData(new Model_Button("UPDATE"));
        btn_xoa.setData(new Model_Button("DELETE"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new com.mycompany.quanlykhoahoc.Component.Card();
        panel = new javax.swing.JLayeredPane();
        btn_them = new com.mycompany.quanlykhoahoc.Component.Card();
        btn_sua = new com.mycompany.quanlykhoahoc.Component.Card();
        btn_xoa = new com.mycompany.quanlykhoahoc.Component.Card();
        panelBorder1 = new com.mycompany.quanlykhoahoc.Component.PanelBorder();

        setBackground(new java.awt.Color(242, 240, 240));

        panel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btn_them.setColor1(new java.awt.Color(142, 142, 250));
        btn_them.setColor2(new java.awt.Color(123, 123, 245));
        panel.add(btn_them);

        btn_sua.setColor1(new java.awt.Color(186, 123, 247));
        btn_sua.setColor2(new java.awt.Color(167, 94, 236));
        panel.add(btn_sua);

        btn_xoa.setColor1(new java.awt.Color(241, 208, 62));
        btn_xoa.setColor2(new java.awt.Color(211, 184, 61));
        panel.add(btn_xoa);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.quanlykhoahoc.Component.Card btn_sua;
    private com.mycompany.quanlykhoahoc.Component.Card btn_them;
    private com.mycompany.quanlykhoahoc.Component.Card btn_xoa;
    private com.mycompany.quanlykhoahoc.Component.Card button1;
    private javax.swing.JLayeredPane panel;
    private com.mycompany.quanlykhoahoc.Component.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
